version: 2.1

executors:
  dotnet-6-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-6-executor

    steps:
      - checkout

      - run:
          name: Restore dependencies

          command: dotnet restore src/CloudSuite.sln

      - run:
          name: Build

          command: dotnet build ./CloudSuite.sln

workflows:
  version: 2

  build-workflow:
    jobs:
      - build
