version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:6.0
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore ./CloudSuite.sln
     - run:
         name: Build App
         command:
           dotnet build ./CloudSuite.sln
     - run:
         name: Run App
         command:
           dotnet run ./CloudSuite.sln