version: 2.1
executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build-and-test:
    executor: dotnet-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build ./CloudSuite.sln

      - run:
          name: Run Tests
          command: dotnet test --logger "trx;LogFileName=test_results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit.*]*%2c[System.*]*"

      - store_test_results:
          path: test_results.trx

      - store_artifacts:
          path: test/**/*.csproj
          destination: test_projects

      - store_artifacts:
          path: test/**/*.trx
          destination: test_results

      - store_artifacts:
          path: coverlet/reports/Cobertura.xml
          destination: code_coverage

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
