version: 2.1

executors:
  dotnet-6-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-6-executor
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore src/**/**/*.csproj

      - run:
          name: Build 
          command: dotnet build src/**/**/*.csproj
      - run:
          name: Test
          command: dotnet test test/**/*.csproj

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - test
