version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dotnet-{{ checksum "src/**/*.csproj" }}-{{ .Branch }}-{{ checksum "src/nuget.config" }}

      - run:
          name: Install dependencies
          command: dotnet restore

      - save_cache:
          key: dotnet-{{ checksum "src/**/*.csproj" }}-{{ .Branch }}-{{ checksum "src/nuget.config" }}
          paths:
            - ~/.nuget/packages

      - run:
          name: Build
          command: dotnet build ./CloudSuite.sln

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dotnet-{{ checksum "src/**/*.csproj" }}-{{ .Branch }}-{{ checksum "src/nuget.config" }}

      - run:
          name: Install dependencies
          command: dotnet restore

      - save_cache:
          key: dotnet-{{ checksum "src/**/*.csproj" }}-{{ .Branch }}-{{ checksum "src/nuget.config" }}
          paths:
            - ~/.nuget/packages

      - run:
          name: Run tests
          command: dotnet test --configuration Release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
