version: 2.1
executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build_ubuntu:
    executor: dotnet-executor
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --configuration Release

      - run:
          name: Test
          command: dotnet test --configuration Release --no-restore

  build_debian:
    executor: dotnet-executor
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --configuration Release

      - run:
          name: Test
          command: dotnet test --configuration Release --no-restore
