version: 2.1

executors:
  dotnet-6-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-6-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build ./CloudSuite.sln

  test:
    executor: dotnet-6-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Run tests
          command: dotnet test --configuration Release

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
