version: 2.1

executors:
  dotnet-6-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-6-executor

    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore CloudSuite.Infrastructure.csproj CloudSuite.Infrastructure.CrossCutting.csproj CloudSuite.Modules.Application.csproj CloudSuite.Modules.Domain.csproj

      - run:
          name: Build
          command: dotnet build CloudSuite.Infrastructure.csproj CloudSuite.Infrastructure.CrossCutting.csproj CloudSuite.Modules.Application.csproj CloudSuite.Modules.Domain.csproj --configuration Release

workflows:
  version: 2

  build-workflow:
    jobs:
      - build
