name: .NET 6 Multi-Stage Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # Use the desired version
        
      - name: Restore dependencies
        run: dotnet restore ./CloudSuite.sln
        
      - name: Build
        run: dotnet build ./CloudSuite.sln
        
      - name: Test
        run: dotnet test test/**/*.Tests.csproj
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # Use the desired version
        
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
    
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      
